---
- hosts: appserver

  tasks:
  - name: Update APT package manager repositories cache
    become: yes
    apt:
      update_cache: yes
  #- name: "apt-get update"
  #  become: yes
  #  apt:
  #    update_cache: yes
  #    cache_valid_time: 3600

  - name: Install OpenJDK Java
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    with_items:
     - ca-certificates
     - openjdk-8-jdk

  - name: ensure the jenkins apt repository key is installed
    become: yes
    ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present

  - name: ensure the repository is configured
    become: yes
    ansible.builtin.apt_repository:
      repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
      state: present



  - name: ensure jenkins is installed
    become: yes
    apt:
        name=jenkins update_cache=yes


  - name: ensure jenkins is running
    become: yes
    service:
        name=jenkins
        state=started

  #- name: Create nginx_backup.sh
  #  become: yes
  #  copy:
  #    dest: "/etc/cron.hourly/nginx_backup.sh"
  #    content: |
  #            #!/bin/bash
  #            scp -r ansible@node1:/etc/nginx/sites-enabled/default ~/default_$(date +%d-%m-%Y)
  #    mode: 0755
  #    owner: ansible
  #    group: ansible


  - name: Create daily backup job
    cron:
      user: 'ansible'
      name: 'nginx_backup'
      minute: "0"
      hour: "17"
      day: '*'
      job: 'scp -r ansible@node1:/etc/nginx/sites-enabled/default ~/default'
      state: present

    #name: "daily nginx config backup"
    #  minute: "21"
    #  hour: "13"
    #  job: "scp -r ansible@node1:/etc/nginx/sites-enabled/default ~/default_$(date +%d-%m-%Y)"